name: 'real_estate'
version: '1.0'
config-version: 2

profile: 'my_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  real_estate:
    +materialized: table
    staging:
      +schema: stg
    intermediate:
      +schema: int
    analytics:
      +schema: analytics